[common]
lib_deps =
  ArduinoJson
  AsyncMqttClient
  ESPAsyncWebServer
  NeoPixelBus
  OneWire
  DallasTemperature

build_flags =
  -DLED_PIN=2
  -DTEMP_PIN=4
  -DDOOR_PIN=5
  -DBUTTON_PIN=0
  -DRELAY_PIN=12

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
extends = common

lib_deps =
  ${common.lib_deps}
  AsyncTCP

build_flags =
  ${common.build_flags}

[env:esp8266]
platform = espressif8266
board = nodemcuv2
framework = arduino
extends = common

lib_deps =
  ${common.lib_deps}
  ESPAsyncTCP

build_flags =
  ${common.build_flags}
